- name: test my new module
  connection: local
  hosts: localhost
  gather_facts: no
  tasks:
  - name: add users and buckets
    ceph_add_users_buckets:
      rgw_host: '172.20.0.2'
      port: 8000
      admin_access_key: 'K0GUB687XXWQ8XJRYOQH'
      admin_secret_key: 'YA73WbFgm2NZIGr4E1OLzv4UKFEG3AjzeICtsx0n'
      users:
        - username: 'test1'
          fullname: 'tester'
          email: 'dan1@email.com'
          maxbucket: 666
          suspend: false
          autogenkey: false
          accesskey: 'B3AR4Q33L59YV56A9A2F'
          secretkey: 'd84BRnMysnVGSyZiRlYUMduVgIarQWiNMdKzrF76'
          userquota: true
          usermaxsize: '1000'
          usermaxobjects: 3
          bucketquota: true
          bucketmaxsize: '1000'
          bucketmaxobjects: 3
        - username: 'test2'
          fullname: 'tester'
      buckets:
        - bucket: 'bucket1'
          user: 'test2'
        - bucket: 'bucket2'
          user: 'test1'
        - bucket: 'bucket3'
          user: 'test1'
        - bucket: 'bucket4'
          user: 'test1'
        - bucket: 'bucket5'
          user: 'test1'
        - bucket: 'bucket6'
          user: 'test1'
        - bucket: 'bucket7'
          user: 'test1'
        - bucket: 'bucket8'
          user: 'test1'
        - bucket: 'bucket9'
          user: 'test1'
        - bucket: 'bucket10'
          user: 'test1'
        - bucket: 'bucket11'
          user: 'test1'
        - bucket: 'bucket12'
          user: 'test1'
        - bucket: 'bucket13'
          user: 'test1'
        - bucket: 'bucket14'
          user: 'test1'
        - bucket: 'bucket15'
          user: 'test1'
        - bucket: 'bucket16'
          user: 'test1'
        - bucket: 'bucket17'
          user: 'test1'
        - bucket: 'bucket18'
          user: 'test1'
        - bucket: 'bucket19'
          user: 'test1'
        - bucket: 'bucket20'
          user: 'test1'
        - bucket: 'bucket21'
          user: 'test1'
        - bucket: 'bucket22'
          user: 'test1'
        - bucket: 'bucket23'
          user: 'test1'
        - bucket: 'bucket24'
          user: 'test1'
        - bucket: 'bucket25'
          user: 'test1'
        - bucket: 'bucket26'
          user: 'test2'
        - bucket: 'bucket27'
          user: 'test2'
        - bucket: 'bucket28'
          user: 'test2'
        - bucket: 'bucket29'
          user: 'test2'
        - bucket: 'bucket30'
          user: 'test2'
        - bucket: 'bucket31'
          user: 'test2'
        - bucket: 'bucket32'
          user: 'test2'
        - bucket: 'bucket33'
          user: 'test2'
        - bucket: 'bucket34'
          user: 'test2'
        - bucket: 'bucket35'
          user: 'test2'
        - bucket: 'bucket36'
          user: 'test2'
        - bucket: 'bucket37'
          user: 'test2'
        - bucket: 'bucket38'
          user: 'test2'
        - bucket: 'bucket39'
          user: 'test2'
        - bucket: 'bucket40'
          user: 'test2'
        - bucket: 'bucket41'
          user: 'test2'
        - bucket: 'bucket42'
          user: 'test2'
        - bucket: 'bucket43'
          user: 'test2'
        - bucket: 'bucket44'
          user: 'test2'
        - bucket: 'bucket45'
          user: 'test2'
        - bucket: 'bucket46'
          user: 'test2'
        - bucket: 'bucket47'
          user: 'test2'
        - bucket: 'bucket48'
          user: 'test2'
        - bucket: 'bucket49'
          user: 'test2'
        - bucket: 'bucket50'
          user: 'test2'


    register: testout
  - name: dump test output
    debug:
      msg: '{{ testout }}'
